using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Months_and_years
{
    public partial class FormFileSelect : Form
    {
        public FormFileSelect()
        {
            InitializeComponent();
        } //Calls InitialseComponents. I'd call them directly, but if I touch the autogenerated code it bites me and then overwrites anything I did. 

        private void buttonSelectFile_Click(object sender, EventArgs e)
        {
            DialogResult result = openFileDialog.ShowDialog();
            if (result == DialogResult.OK)
            {
                fileOpenBox.Text = openFileDialog.FileName;
                
            }
        } // Brings up a file selection dialogue, then copies the selected file into the relevant box on the form.

        private void buttonLaunch_Click(object sender, EventArgs e)
        {
            Location[] data = Filehandler.ReadFile(fileOpenBox.Text);
            if (data.Length != 0)
            {
                var formLocationDisplay = new FormLocationDisplay(data);
                formLocationDisplay.Location = this.Location;
                formLocationDisplay.StartPosition = FormStartPosition.Manual;
                this.Hide();
                formLocationDisplay.Show();
            }
            else
            {
                Console.WriteLine("Invalid file selection");
                fileOpenBox.Text = "Invalid file was selected.";
            }
        } // Reads the selected file from the text box and atempts to ReadFile using the file handler. If the filehandler errors (indicated by an array length 0) outputs an error. 
        // Otherwise, it launches a location display form, passing it the data read from the file and setting its position equal to the current position.
    }
}
