using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Months_and_years
{
    public partial class FormFileSelect : Form
    {
        public FormFileSelect()
        {
            InitializeComponent();
        } //Calls InitialseComponents. I'd call them directly, but if I touch the autogenerated code it bites me and then overwrites anything I did. 

        private void openFileDialog1_FileOk(object sender, CancelEventArgs e)
        {

        } // Nothing happens in here. This code was auto-generated, and unless you're willing to engage with tomfoolery with the design tool, it stays.

        private void buttonSelectFile_Click(object sender, EventArgs e)
        {
            DialogResult result = openFileDialog.ShowDialog();
            if (result == DialogResult.OK)
            {
                fileOpenBox.Text = openFileDialog.FileName;
                Location[] data = Filehandler.ReadFile(openFileDialog.FileName);
                var formLocationDisplay = new FormLocationDisplay(data);
                formLocationDisplay.Location = this.Location;
                formLocationDisplay.StartPosition = FormStartPosition.Manual;
                this.Hide();
                formLocationDisplay.Show();
            }
        } // Brings up a file selection dialogue. If the dialogue gets a file, then it gets read in via the filehandler and passed to a new LocationDisplay form along with the current position of this form.
        //If the user selects an invalid file, either the filehandler throws an error and kicks the user back to this screen or the file selector says 'not okay' and the user stays on this form anyway.

        private void Form1_Load(object sender, EventArgs e)
        {

        } // Nothing happens here when the form loads. This code was auto-generated, and unless you're willing to engage with tomfoolery with the design tool, it stays.

    }
}
